### PR TITLE
Fixed #735: removed unnecessary eval against Security

### LINKED ISSUE #725: Use / in triggers-config.sample.xml
The triggers sample xml uses `/triggers/` as modules-root, causing confusion among users when imports are not found, due to unfamiliarity with what modules-root does. I'd recommend using / as modules-root, and the full path to the .xqy in the triggers sample file..

### LINKED ISSUE #735: replicating Security DB results in failed bootstrap
#### The issue

Short description of the problem:

When you try to replicate the Security database as part of a bootstrap  you can see that when the Security db goes offline the bootstrap seems to continue and gets into a kind of death loop trying to lookup details in the Security db. Here is a sample of the output in the ML ErrorLog.txt.

```
2017-02-09 14:20:12.583 Debug: Retrying HTTPRequestTask::handleXDBCEval eval 8527616213787243855 Update 90 because XDMP-FORESTNOT: Forest Security not available: middle closing
2017-02-09 14:20:14.487 Debug: Retrying ForestReindexerThread::reindexFragments Last-Login 28 because XDMP-FORESTNOT: Forest Security not available: middle closing
2017-02-09 14:20:14.843 Debug: Retrying HTTPRequestTask::handleXDBCEval eval 8527616213787243855 Update 91 because XDMP-FORESTNOT: Forest Security not available: middle closing
2017-02-09 14:20:15.918 Debug: Retrying ForestReindexerThread::reindexFragments Modules 28 because XDMP-FORESTNOT: Forest Security not available: middle closing
2017-02-09 14:20:16.961 Debug: Retrying HTTPRequestTask::handleXDBCEval eval 8527616213787243855 Update 92 because XDMP-FORESTNOT: Forest Security not available: middle closing
2017-02-09 14:20:16.975 Debug: Retrying ForestReindexerThread::reindexFragments Meters 30 because XDMP-FORESTNOT: Forest Security not available: middle closing
2017-02-09 14:20:17.350 Debug: Retrying ForestReindexerThread::reindexFragments Schemas 29 because XDMP-FORESTNOT: Forest Security not available: middle closing
2017-02-09 14:20:17.819 Debug: Retrying ForestReindexerThread::reindexFragments Fab 25 because XDMP-FORESTNOT: Forest Security not available: middle closing
2017-02-09 14:20:18.728 Debug: Retrying ForestReindexerThread::reindexFragments App-Services 27 because XDMP-FORESTNOT: Forest Security not available: middle closing
2017-02-09 14:20:18.831 Debug: Retrying ForestReindexerThread::reindexFragments Documents 28 because XDMP-FORESTNOT: Forest Security not available: middle closing
2017-02-09 14:20:19.528 Debug: Retrying HTTPRequestTask::handleXDBCEval eval 8527616213787243855 Update 93 because XDMP-FORESTNOT: Forest Security not available: middle closing
2017-02-09 14:20:21.655 Debug: Retrying ForestReindexerThread::reindexFragments Triggers 27 because XDMP-FORESTNOT: Forest Security not available: middle closing
2017-02-09 14:20:21.798 Debug: Retrying HTTPRequestTask::handleXDBCEval eval 8527616213787243855 Update 94 because XDMP-FORESTNOT: Forest Security not available: middle closing
2
```

What are the steps to reproduce the problem?

Create a 3 node cluster using Docker , Red Hat SLES 6, ML 8.0-6.1. My host laptop is Mac OS X. Download and create a vanilla roxy project. Set ```systems-dbs=Security```. Run the bootstrap as below , eventually you will see the error message below. 

```
~/Workspace/Haufe/test-app -> ml local bootstrap --replicate-internals
Bootstrapping replicas for Security on localhost...
ERROR: 500 "Internal Server Error"
ERROR: {"errorResponse":{"statusCode":500, "status":"Internal Server Error", "messageCode":"XDMP-FORESTNOT", "message":"XDMP-FORESTNOT: Forest Security not available: middle closing", "messageDetail":{"messageTitle":"Forest not available"}}}

```

Here is my ```local.properties```

```
test-content-db=${app-name}-content-test
test-modules-db=${app-name}-modules
test-port=8072
test-authentication-method=digest
content-forests-per-host=1
system-dbs=Security

```

#### Tech Specs

Which Operating System are you using?

SLES 6

Which version of MarkLogic are you using?

8.0-6.1

Which version of Roxy are you using (see version.txt)?

1.7.5

### PR DESCRIPTION
**Pull request by grtjn**
Fixes #735

### CODE REVIEW

**Comment by RobertSzkutak** [comment]
No issues with self-test. Appears to work just fine.

**Comment by joecrean** [comment]
sorry @grtjn you were too quick for me there. I looked at this before lunch but it was merged by the time i came back :-)
In any case the solution is indeed interesting a) that it makes such a difference when we try to test which role we have and b) the guard against replicating internals... I am not sure we even set that option..

**Comment by grtjn** [comment]
The internals flag is set by roxy automatically if you pass in the replicate internals argument..

**Comment by jamsilvia** [comment]
So, this was added as part of the review for my pull request on the original changes.  I'll quote the comments below.  I just want to make sure Robert's original concerns are properly dealt with in your proposed changes. 

> **RobertSzkutak:** Could you explicitly force permissions on these? Some folks I know bootstrap with highly privileged users rather than admins. Maybe something like:
> 
> if(user is admin) then admin read and admin update 
> else if(xdmp:default-permissions()) then xdmp:default-permissions() 
> else (xdmp:permission()))
> 
> **jamsilvia:** I checked in an update to setup.xqy that hopefully addresses your concern. I didn't create and permission if the default wasn't there - at that point, I wouldn't know what permission to explicitly use. So I stopped at default-permission.

**Comment by RobertSzkutak** [comment]
@jamsilvia In retrospect its probably a cleaner solution for people to have to set their own default permissions if they dont exist.

**Comment by grtjn** [comment]
I'll append comments about doc permissions of map files to #772. I can now see the point of wanting to force doc permissions, but we could also just check for empty default permissions, and warn about that. Doc permissions for an admin user is not the way for sure.. :)

**Comment by jamsilvia** [comment]
Fair enough, @RobertSzkutak!  It sounds like it is covered then.

**Pull request merged**
