### PR TITLE
#415 adding "deploy rest config" command

### PR DESCRIPTION
**Pull request by dmcassel**
#415

### CODE REVIEW

**Comment by grtjn** [comment]
Looks good to me.. (haven't tried though)

**Comment by dmcassel** [comment]
Can someone give this a test run?

**Comment by grtjn** [comment]
These changes are that small, I'd say just merge. You are basically only getting rid of a param that isn't used anyhow.. :)

**Comment by grtjn** [comment]
Waited long enough, merging now..

**Pull request merged**
