### PR TITLE
Fixed #383, #380, #379, #378

### LINKED ISSUE #378: Forest replication doesn't work unless forests-per-host
Not implemented, but adding forests-per-hosts for databases like modules doesn't make much sense..

### LINKED ISSUE #379: Replication forests not created once forests exists

### LINKED ISSUE #380: Ignore replica forests when bootstrapping to standalone
replica forests needs a cluster of at least two hosts. Silently ignoring replica forests makes simpler running same config on local dev instance..

### LINKED ISSUE #383: Reassigning replicas doesn't spread replicas
When you have multiple replicas for one forest, they all end up on the next host, instead of being spread over all following..

### PR DESCRIPTION
**Pull request by grtjn**
* Fixed #383: Using multiple replica-names for one forests will make them spread over different following hosts, not all on the same.
* Fixed #380: You need multiple hosts for forest replication. If you bootstrap against a single host, forest-replication is silently ignored (under assumption you are doing a test deployment on localhost or dev)
* Fixed #379: If you later decide you want forest replication, the code to add them to existing forests was skipped. Necessary for adding rep to system databases.
* Fixed #378: Forest replication was only applied if `<forests-per-host>` was used. Now also works without.

### CODE REVIEW

**Comment by grtjn** [comment]
Sorry for piling up changes for 4 tickets, but they were very closely related. I can provide a sample ml-config to test this..

**Comment by rlouapre** [comment]
+1
Any idea when this PR will be merged

**Comment by grtjn** [comment]
@rlouapre You can pull this locally using upgrade: `ml upgrade --fork=grtjn --branch=forest-rep-improvements`

**Comment by dmcassel** [comment]
@rlouapre, it hasn't been merged because neither @paxtonhare nor I have had a chance to test it. Have you tried out these changes?

**Comment by grtjn** [comment]
You can relatively easy test this and #366 as well by following these steps:

- create a cluster of at least 2 nodes, you can use mlvagrant for this
- create a roxy or slush project, and configure it to point to the cluster
- run: `./ml upgrade --fork=grtjn --branch=366-replicate-internals`
- edit ml-config.xml, and change the assignments section into:
```xml
  <assignments xmlns="http://marklogic.com/xdmp/assignments" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://marklogic.com/xdmp/assignments assignments.xsd">
    <assignment>
      <forest-name>@ml.content-db</forest-name>
      <replica-names>
        <replica-name>@ml.content-db-rep1</replica-name>
      </replica-names>
      @ml.forest-data-dir-xml
    </assignment>
    <assignment>
      <forest-name>@ml.content-db-rep1</forest-name>
      @ml.forest-data-dir-xml
    </assignment>
    @ml.test-content-db-assignment
    @ml.test-modules-db-assignment
    @ml.rest-modules-db-assignment
    <assignment>
      <forest-name>@ml.modules-db</forest-name>
      <replica-names>
        <replica-name>@ml.modules-db-rep1</replica-name>
      </replica-names>
    </assignment>
    <assignment>
      <forest-name>@ml.modules-db-rep1</forest-name>
    </assignment>
    @ml.schemas-assignment
    @ml.triggers-assignment
  </assignments>
```
- run: `./ml local bootstrap`
- run: `./ml local bootstrap --replicate-internals`

The end result should be that all forests have a local replica failover.

**Comment by rlouapre** [comment]
Just see this PR has been merged.

Tested it successfully on a simple 3 nodes cluster.

A couple of questions:
- I need to create a replica-name for each node of the cluster. Would it be possible to **discover** all nodes of the cluster and create replica forest on each node except the current node?
```xml
<forest-name>@ml.content-db</forest-name>
      <replica-names>
        <replica-name>@ml.content-db-rep1</replica-name>
        <replica-name>@ml.content-db-rep2</replica-name>
      </replica-names>
```  
- I assume Roxy deployment script will not changed existing forests setup. Would it be possible to change this behavior so that Roxy script managed the replica forest settings?  Scenario: new nodes are added to the cluster re-run ```bootstrap``` will create forest and replicas on new nodes.

**Comment by grtjn** [comment]
@rlouapre Keep in mind that for databases with a forests-per-host setting, a forest is created on each host of the target group, and for each forest a replica would be created. It doesn't make sense to create n replicas for each forest. That would completely kill the performance of the cluster. Each replica adds 100% IO for that forest.

Yes, Roxy bootstrap is designed to keep things in place as much as possible, and only add changes. If you started with 3 nodes, did a bootstrap, and then add node 4, you can rerun bootstrap to add more forests. I haven't tried how well that works with replica forests. Rep forests might get redistributed, not sure how well that works..

If this still leaves questions or issues, maybe open new tickets..

**Pull request merged**
