### PR TITLE
Fixed #661: wrap app_name query in xdmp:eval to provide appropriate context

### LINKED ISSUE #661: Allow execute_query with app_name set to ml.app-name
I changed execute_query_8 as shown below, and that allows me to at least invoke modules of current project with for instance:

```
  def replace_addresses
    country = find_arg(["--country"]) || "NL"
    lang = find_arg(["--language"]) || "Dutch"
    logger.info "Replacing customer addresses with #{country}/#{lang}.."
    r = execute_query(
      %Q{
        xquery version "1.0-ml";
        xdmp:invoke('/task/replace-addresses.xqy', (xs:QName("country"), "#{country}", xs:QName("lang"), "#{lang}"))
      },
      { :app_name => @properties["ml.app-name"] }
    )
    r.body = parse_body(r.body)
    logger.info r.body
  end
```

Patch for server_config.rb:

``` ruby
  def execute_query_8(query, properties = {})
    if properties[:app_name] != nil && properties[:app_name] != @properties["ml.app-name"]
      raise ExitException.new("Executing queries with an app_name (currently) not supported with ML8+")
    end

    headers = {
      "Content-Type" => "application/x-www-form-urlencoded"
    }

    params = {
      :xquery => query,
      :locale => LOCALE,
      :tzoffset => "-18000"
    }

    port = @qconsole_port
    if properties[:app_name] != nil
      port = @properties["ml.app-port"]
    end
    if properties[:db_name] != nil
      params[:database] = properties[:db_name]
    end

    r = go "#{@protocol}://#{@hostname}:#{port}/v1/eval", "post", headers, params

    raise ExitException.new(JSON.pretty_generate(JSON.parse(r.body))) if r.body.match(/\{"error"/)

    r
  end
```

### PR DESCRIPTION
**Pull request by grtjn**
Fixes #661

### CODE REVIEW

**Comment by grtjn** [comment]
In case someone wonders, a simple way to run a quick test is to copy the execute_query_8 into app_specific.rb, and run the test code I provided in this comment of #661: https://github.com/marklogic/roxy/issues/661#issuecomment-281598395

**Comment by RobertSzkutak** [comment]
Having two problems with this PR...

1) On the latest version of ML8, the code throws this error:
ERROR: 500 "Internal Server Error"
ERROR: {"errorResponse":{"statusCode":500, "status":"Internal Server Error", "messageCode":"XDMP-UNDFUN", "message":"XDMP-UNDFUN: (err:XPST0017) Undefined function xdmp:server-coordinate-system()", "messageDetail":{"messageTitle":"Undefined function"}}}

Seems like to fix this its time to finally introduce execute_query_9 ...

2) When I set the db_name param to something other than the app content db (the value used in your second test) on the latest ML8 it throws this error:
ERROR: 500 "Internal Server Error"
ERROR: {"errorResponse":{"statusCode":500, "status":"Internal Server Error", "messageCode":"XDMP-NODB", "message":"XDMP-NODB: xdmp:database-name(xs:unsignedLong(\"0\")) -- No database with identifier 0", "messageDetail":{"messageTitle":"No database"}}}

Too tired to figure this one out I will try to debug it in the morning.

**Comment by grtjn** [comment]
Thanks, good finds. I should have tested my code against other than latest. I'll poke some more at this..

**Comment by grtjn** [comment]
Issue 2 might just be bad test code. The bit of code I referred to above tries to get the database-name, but does not anticipate modules-db being set to (file system), which is the case for no params, since that reverts to the Manage app-server. Use this code instead:

```
  def test
    logger.info "Execute query with no params:"
    r = execute_query(
      %Q{
        xquery version "1.0-ml";

        declare function local:database-name($id) {
          if ($id eq 0) then
            "(file system)"
          else
            xdmp:database-name($id)
        };

        "content-db: " || local:database-name(xdmp:database()),
        "modules-db: " || local:database-name(xdmp:modules-database()),
        "schemas-db: " || local:database-name(xdmp:schema-database()),
        "trigger-db: " || local:database-name(xdmp:triggers-database())
      }
    )
    r.body = parse_body r.body
    logger.info r.body
    logger.info ""

    logger.info "Execute query with db_name param:"
    r = execute_query(
      %Q{
        xquery version "1.0-ml";

        declare function local:database-name($id) {
          if ($id eq 0) then
            "(file system)"
          else
            xdmp:database-name($id)
        };

        "content-db: " || local:database-name(xdmp:database()),
        "modules-db: " || local:database-name(xdmp:modules-database()),
        "schemas-db: " || local:database-name(xdmp:schema-database()),
        "trigger-db: " || local:database-name(xdmp:triggers-database())
      },
      { :db_name => @properties['ml.content-db'] }
    )
    r.body = parse_body r.body
    logger.info r.body
    logger.info ""

    logger.info "Execute query with app_name param:"
    r = execute_query(
      %Q{
        xquery version "1.0-ml";

        declare function local:database-name($id) {
          if ($id eq 0) then
            "(file system)"
          else
            xdmp:database-name($id)
        };

        "content-db: " || local:database-name(xdmp:database()),
        "modules-db: " || local:database-name(xdmp:modules-database()),
        "schemas-db: " || local:database-name(xdmp:schema-database()),
        "trigger-db: " || local:database-name(xdmp:triggers-database())
      },
      { :app_name => @properties['ml.app-name'] }
    )
    r.body = parse_body r.body
    logger.info r.body
    logger.info ""
  end
```

Also make sure you bootstrap before you run that test, otherwise mentioned values will be wrong (details for Manage or some random app-server).

I'm investigating running exec_8 against ML8..

**Comment by grtjn** [comment]
This should work better..

I'm printing warnings for ml7- if a referenced db_name or app_name is not found. The execute_query_5/7 seemed to be very forgiving, a bit too much I think.

The execute_query_8 however is not forgiving, no fallback if db_name or app_name refers to non-existing items. I added a check upfront, and raise an exception if non-existing. The effect is similar if we don't do this, but the feedback for the user is cleaner this way.

I also applied a trick with fn:function-lookup to be server-version agnostic. All seems to run smooth against ml7, ml8, and ml9 now..

**Comment by grtjn** [comment]
@RobertSzkutak Can you give it another spin?

**Comment by RobertSzkutak** [comment]
Everything looks good!

**Pull request merged**
