### PR TITLE
Fix a bug in Roxy that doesnt let non-admin users deploy modules

### PR DESCRIPTION
**Pull request by RobertSzkutak**
See Issue https://github.com/marklogic/roxy/issues/514

### CODE REVIEW

**Comment by grtjn** [comment]
Perfect! I'll run a quick test with this tomorrow..

**Comment by RobertSzkutak** [comment]
Thanks for the quick feedback. Highly appreciated :+1:

**Comment by grtjn** [comment]
Oh wait, can you do a favor, and redo this work on top of the dev branch?

Maybe also worth having a quick look on our (CONTRIBUTING)[https://github.com/marklogic/roxy/blob/master/CONTRIBUTING.md] file, there are some useful steps in there that can help do PR's smartly.

**Comment by RobertSzkutak** [comment]
Sure, no problem. Thanks for the reference guide too!

**Comment by grtjn** [comment]
Closing this one in favor of #518..

**Pull request closed without merging**
