### PR TITLE
Fixing issue #535: Search for forest names in clean

### PR DESCRIPTION
**Pull request by jmeekhof**
clean command was failing when cleaning an enviroment that wasn't
originally bootstrapped by roxy.

I modified the clean_modules routine to search for forests associated
with the modules database instead of assuming the default forest name.

### CODE REVIEW

**Comment by joemfb** [comment]
looks good to me, thanks!

(re #535)

**Comment by dmcassel** [comment]
@jmeekhof thanks for submitting this

**Comment by grtjn** [comment]
@dmcassel Shouldn't we be merging this instead of closing this? :)

**Comment by dmcassel** [comment]
Doh. Sorry about that.

**Pull request merged**
