### PR TITLE
Capture/redirect on exit and provide unique return codes, fix for issue #543

### PR DESCRIPTION
**Pull request by danielritchie**
### deploy/lib/ml.rb
***deploy/lib/ml.rb*** presently exits with errors using "exit!" This forces an immediate exit that bypasses [SystemExit](http://ruby-doc.org/core-1.9.3/SystemExit.html) handling and returns "1".  Using this method also causes something strange to happen with the output of the script, preventing redirection and other concerns [See: Issue #543](https://github.com/marklogic/roxy/issues/543)

**All "exit!" calls have been replaced with "exit #"** as I couldn't see any reason why the use of return codes would be problematic.  I believe this maintains all existing functionality, and is a desirable enhancement.

**Two "exit" calls were also replaced with a unique return code** THIS WILL CHANGE EXIT BEHAVIOR ("exit" alone will return 0).  Although I don't see any reason this addition would be undesired, I wanted to call it out since it does modify the return code.

More detail from Ruby docs:
[exit](http://ruby-doc.org/core-1.9.3/Kernel.html#method-i-exit) vs. [exit!](http://ruby-doc.org/core-1.9.3/Kernel.html#method-i-exit-21)
[SystemExit](http://ruby-doc.org/core-1.9.3/SystemExit.html)

###  ml
**ml** has been modified to exit with actual return code from deploy/lib/ml.rb instead of defaulting to 1

### CODE REVIEW

**Comment by danielritchie** [comment]
Have confirmed that when using this fix the output is returned as expected when executing from Jenkins

**Comment by dmcassel** [comment]
Regarding the two exit calls replaced with exit and a return code -- that looks like a good thing to me, as exit code 0 is typically success.

**Comment by dmcassel** [comment]
I ran some tests and this looks good. One thing that might be useful as a future change is replace the literal numbers with constant values, to make it easier to look up the error codes. 

@danielritchie thanks for submitting this!

**Comment by danielritchie** [comment]
@dmcassel your wish has been at least partially graned with #547 :)

**Pull request merged**
