### PR TITLE
PREP to use constanst for exit codes

### PR DESCRIPTION
**Pull request by danielritchie**
Follow up on comment by @dmcassel when working through https://github.com/marklogic/roxy/pull/546

It was easy for me with everything open to perform a few quick substitutions.  Past that, I attempted to confirm Ruby syntax but wasn't 100% sure I got it right.  I also don't have a good environment setup for testing this.  Having said that, if it doesn't work as-is, the placeholders are staged so it should be ready to go for any changes you would like to make.

  - replaced all hard-coded exit codes with constants
  - set usage to return 0 if help requested
  - shifted codes to avoided using reserved bash return codes

### CODE REVIEW

**Comment by paxtonhare** [comment]
@danielritchie can you take off that out.test file?

**Comment by danielritchie** [comment]
@paxtonhare done

**Comment by dmcassel** [comment]
Minor typo: could you replace EXIT_RESCUE_EXCPTION with EXIT_RESCUE_EXCEPTION?

**Comment by danielritchie** [comment]
@dmcassel var name replaced as requested

**Pull request merged**
