### PR TITLE
Adding folders_to_ignore property

### PR DESCRIPTION
**Pull request by miguelrgonzalez**
Folders_to_ignore now at dev branch

### CODE REVIEW

**Comment by grtjn** [comment]
Hmm, pity. Can't automatically merge. I think it is because your dev branch wasn't holding the latest from marklogic/roxy dev branch. Can you try:

```sh
$ git fetch upstream
$ git rebase upstream/develop
```

And then git push to append to your pull-request?

**Comment by miguelrgonzalez** [comment]
Hi Geert,
I had quite a mess on my local git. I was forgot to update my local dev
branch with the latest and was basing my commit on really old commit ....

anyway, I think it's fixed now.

Cheers,
Miguel

**Comment by grtjn** [comment]
Yes, result looks good. @paxtonhare or @dmcassel care to click the Merge button?

**Comment by miguelrgonzalez** [comment]
I just reread my latest message .... I'm not sure what it's more messy, my
former commit, or the message itself :)

**Pull request merged**
