### PR TITLE
#601 adding quotes around the ruby path

### PR DESCRIPTION
**Pull request by dmcassel**
#601

### CODE REVIEW

**Comment by grtjn** [comment]
Looks good. Would have to grab hold of my win laptop to test this..

**Comment by dmcassel** [comment]
Can someone test this on Windows?

**Comment by rlouapre** [comment]
That seems to fix the issue - but please also note my comment. There are best practices on the installing Ruby on Windows...

**Comment by dmcassel** [comment]
@rlouapre thanks for the test. While acknowledging the best practice, it looks like this is still a useful change.

**Pull request merged**
