### PR TITLE
Issue 585: group settings

### PR DESCRIPTION
**Pull request by rlouapre**
Add group settings for module-location, namespace, schema, trace-event, using-namespace. #585

### CODE REVIEW

**Comment by grtjn** [comment]
Looks good at first glance. I'll try to run a self-test tomorrow..

**Comment by grtjn** [comment]
Merge conflict, please rebase?

**Comment by dmcassel** [comment]
@grtjn have you tested this? I might be able to handle the conflicts if you've verified that the changes are good.

**Comment by grtjn** [comment]
I apparently failed to run those promised tests. Let me retry this week..

**Comment by grtjn** [comment]
Odd, github says this is a merge from `unknown repository`. Did a rebase fail perhaps, or was the branch deleted on the other side?

Anyhow, I pulled in change via manual merge steps. One patch couldn't be applied automatically, but it was a simple change. Self-test ran clean against a single host.

**Comment by grtjn** [comment]
Self-test runs clean against my 3-node test cluster as well. If we can get this rebased, we could merge. Or if that is tricky, we should try to merge manually.

**Comment by rlouapre** [comment]
I have rebase a couple of time already... I will provide an update soon.

**Comment by rlouapre** [comment]
New PR #676

**Comment by dmcassel** [comment]
Replaced by a new PR, so closing this one.

**Pull request closed without merging**
