### PR TITLE
FIX #514

### LINKED ISSUE #514: XDMP-MUSTHAVEUPDATE when deploying modules with account that doesnt have admin role
Hi,

Whenever I try to deploy modules with an account that's not admin I get the error XDMP-MUSTHAVEUPDATE

```
bobby@lionsden ~/projects/twitter
$ ./ml local deploy modules -v
source permissions: [{:capability=>"E", :role=>"twitter-role"}, {:capability=>"R", :role=>"twitter-role"}, {:capability=>"R", :role=>"rest-admin"}, {:capability=>"U", :role=>"rest-admin"}, {:capability=>"E", :role=>"rest-extension-user"}]
Using Batch commit: false
loading: /home/bobby/projects/twitter/src/lib/twitter.xqy => /lib/twitter.xqy
[PUT]   http://localhost:8044/insert?uri=%2Flib%2Ftwitter.xqy&perm=Etwitter-role&perm=Rtwitter-role&perm=Rrest-admin&perm=Urest-admin&perm=Erest-extension-user&tzoffset=-18000&dbname=twitter-modules
[GET]   http://localhost:8002/manage/LATEST/databases?format=xml
[POST]  http://localhost:8000/qconsole/endpoints/workspaces.xqy
Closing HTTP connection to localhost:8002
[POST]  http://localhost:8000/qconsole/endpoints/evaler.xqy?wsid=8992296078432323301&qid=5563066314083214850&action=eval&querytype=xquery&dirty=true&dbid=13208991071066605692
[DELETE]        http://localhost:8000/qconsole/endpoints/workspaces.xqy?wsid=8992296078432323301

Loaded 1 document from /home/bobby/projects/twitter/src to localhost:8044/twitter-modules at 09/17/2015 04:13:28 pm

[PUT]   http://localhost:8043/v1/config/properties
Using Batch commit: false
loading: /home/bobby/projects/twitter/rest-api/config/options/all.xml => /Default/twitter/rest-api/options/all.xml
[PUT]   http://localhost:8044/insert?uri=%2FDefault%2Ftwitter%2Frest-api%2Foptions%2Fall.xml&perm=Etwitter-role&perm=Rtwitter-role&tzoffset=-18000&dbname=twitter-modules
ERROR: 500 "Internal Server Error"
ERROR: 
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>500 Internal Server Error</title>
          <meta name="robots" content="noindex,nofollow"/>
          <link rel="stylesheet" href="/error.css"/>
        </head>
      <body>
        <span class="error">
      <h1>500 Internal Server Error</h1>
      <dl>
        <dt>XDMP-MUSTHAVEUPDATE: Document must have at least one update permission. Assigned permissions: %1</dt>
        <dd></dd>
        <dt> [1.0-ml]</dt>
        <dd></dd>
      </dl>
    </span>
  </body>
</html>
```

I added this to line 231 of xcc.rb to make the error go away:

```
url << "&perm=Utwitter-role"
```

I have never written a single line of Ruby in my life before today so I apologize for not writing a proper fix as I was in a pinch to get this working for a customer. I've also tested this on a completely brand new roxy project to make sure that I didn't have any settings that were not default.

### PR DESCRIPTION
**Pull request by jmeekhof**
Update to allow non-admin users to deploy.

### CODE REVIEW

**Comment by grtjn** [comment]
I think this might need to be piled on top of #518, but not entirely sure. ERU was introduced there, didn't exist before yet..

**Comment by jmeekhof** [comment]
@grtjn You are correct. It's related to the same issue. I believe the #518 fixed a deploy for REST extensions, and this is module / content deploy issue
.

**Comment by jmeekhof** [comment]
has this been merged, but the Pull Request left open?

**Comment by dmcassel** [comment]
This one hasn't been merged yet, but I just looked and the only non-whitespace change is adding update permission in one spot. I'll merge it.

**Comment by jmeekhof** [comment]
Cool, thanks. BTW, the white space changes all follow the .editorconfig settings, so that's a good think too.

**Comment by dmcassel** [comment]
Yes, I was happy to see those.

**Pull request merged**
