### PR TITLE
Fix #591: overriding property from command line

### LINKED ISSUE #591: Issue when overriding property from command line
Assuming ```{env}.properties``` contains 
```properties
xcc-port=9999
dummy-port=${xcc-port}
```

And running ./ml {env} info --ml.xcc-port=8888 will output
```
xcc-port=8888
dummy-port=9999
```
Property substitution happens before properties are extracted from command line.

### PR DESCRIPTION
**Pull request by rlouapre**
#591

### CODE REVIEW

**Comment by grtjn** [comment]
Looks clean..

**Comment by RobertSzkutak** [comment]
Hello @rlouapre ! I would be happy to merge this in if you could make one change for me.

deploy/lib/server_config.rb looks good.

However the changes to the other two files deploy/test/data/ml7-properties/build.properties and deploy/test/test_server_config.rb look to be made for your own personal testing.

If you could remove your changes from these files I'd be happy to merge in this request. If you're too busy, I'm also happy to commit in only just the changes in server_config.rb so we can close out the issue.

Thanks for your PR!

**Comment by grtjn** [comment]
I actually think they are valid additions to the self-test..

**Comment by RobertSzkutak** [comment]
Tested out and it seems fine. Following your advice @grtjn  and merging..

**Pull request merged**
