### PR TITLE
#648 check whether we're using the filesystem for modules

### PR DESCRIPTION
**Pull request by dmcassel**
#648

### CODE REVIEW

**Comment by grtjn** [comment]
Bootstrap runs great, but wipe complains too. Can you look at that as well? :P

**Comment by dmcassel** [comment]
Good catch, will fix.

**Comment by dmcassel** [comment]
Fixed. Successfully wipes just the targeted scheduled tasks.

**Comment by grtjn** [comment]
Using `./ml upgrade --fork=dmcassel --branch=issue-648` to test..

**Comment by RobertSzkutak** [comment]
This only works if the task-modules database is set to filesystem. It still fails if the task-content database is set to filesystem.

**Comment by grtjn** [comment]
Bootstrap and wipe failed before, but after upgrade both run fine..

**Comment by dmcassel** [comment]
@RobertSzkutak we don't allow for content databases on the filesystem; it's just an issue for modules.

**Comment by grtjn** [comment]
I'm merging!

**Pull request merged**
