### PR TITLE
#656 Support JavaScript setup/suite-setup/teardown/suite-teardown

### PR DESCRIPTION
**Pull request by bradmann**
JavaScript is awesome.

### CODE REVIEW

**Comment by RobertSzkutak** [comment]
Pinging @grtjn and @dmcassel for an opinion as I'm not very familiar with the testing framework.

I feel like the best way to handle this would be with a variable in src/test/test-config.xqy to pick whether you want XQY or SJS. Could there ever be a scenario in which you would want to invoke both? Lastly, I think we would need sample SJS files in the repository to keep it newbie friendly.

On the surface, I think this absolutely benefits Roxy even if we would need to do some more work on it. I'll defer to someone else about whether our preferred process would be to first perfect the PR or merge and finish it later.

**Comment by dmcassel** [comment]
I'll try to poke at it this week.

**Comment by bradmann** [comment]
I've already coded a solution and submitted a pull request against dev.

**Comment by dmcassel** [comment]
Rephrasing -- I'll check out your PR this week

**Comment by dmcassel** [comment]
A couple things (nothing big):

- on [default.xqy line 456](https://github.com/bradmann/roxy/blob/77452b9cea62d8dd0b96fecec8659da01356f342/src/test/default.xqy#L456), there's a test to see whether a file should be considered a test. Since suite-setup.sjs and suite-teardown.sjs are not part of that test, they show up as unit tests and are executed as such (in addition to be run correctly as suite setup/teardown). 
- aren't filenames in JavaScript land more often camelCased? I'm thinking it would be more consistent to call these suiteSetup.sjs and suiteTeardown.sjs. (I know there isn't really a convention, I just think it makes sense to match the filename to what we do inside the file. Other opinions welcome, but absent consensus in the other direction, I'd like to see the filenames changed.)

Otherwise, this looks great.

**Comment by bradmann** [comment]
changes made.

**Pull request merged**
