### PR TITLE
issue 585

### PR DESCRIPTION
**Pull request by rlouapre**
Manually tested: module-location, namespace, schema on ML 8.0-4.2. #585

### CODE REVIEW

**Comment by dmcassel** [comment]
@grtjn I think you've done the most with group settings; how does this look to you?

**Comment by grtjn** [comment]
Looks like smart code to me. Interesting thought to leverage new attributes on the setting elements. Definitely need to run self-test with this (e.g. I think we need to extend ml7-config.xml), and I'd like to take a closer look at the xdmp:value logic as well..

**Comment by rlouapre** [comment]
I am happy to provide some tests but I have done it long time ago and I cannot remember how to run them and what to implement.  
Do we have documentation on how to write and run the tests?

**Comment by grtjn** [comment]
It is the self-test command (`./ml self-test`). It by default runs with the deploy/test/data/ml7-config.xml (which we also use to test ml8 at the moment) against localhost. You can put a local.properties in deploy/test/data/ml7-properties/ to override that if necessary..

**Comment by grtjn** [comment]
Not aware of documentation on self-test unfortunately..

**Comment by rlouapre** [comment]
Some fixes and new validation used by ```self-test```. See new PR #590

**Comment by grtjn** [comment]
Funny, you normally don't need a new PR to append commits to it..

**Comment by rlouapre** [comment]
Agree. Not sure what happens...

**Comment by grtjn** [comment]
Closing this in favor of #590..

**Pull request closed without merging**
