### PR TITLE
Issue 591: command-line properties

### PR DESCRIPTION
**Pull request by rlouapre**

### CODE REVIEW

**Comment by grtjn** [comment]
Looks good at first glance..

**Comment by dmcassel** [comment]
This PR addresses multiple issues. It's easier to review and accept PRs that address one thing at a time. 

I've tested the parameter override (#591), but not the group setting changes.

**Comment by grtjn** [comment]
Merge conflict. Rebase please?

**Comment by grtjn** [comment]
Hmm, looks like commits from multiple PR's are piled up in here. Is it possible to take out the non-relevant ones?

**Comment by grtjn** [comment]
Need help with rebasing?

**Comment by rlouapre** [comment]
Closing. See new PR 643

**Pull request closed without merging**
