### PR TITLE
Dev Branch fix for Issue 514

### PR DESCRIPTION
**Pull request by RobertSzkutak**
https://github.com/marklogic/roxy/issues/514

### CODE REVIEW

**Comment by grtjn** [comment]
Bit odd to merge a fork from master into dev, but the diff looks clean.

**Comment by grtjn** [comment]
I ran a few tests, and once I started inheriting rest-admin role, I could deploy modules without trouble. I double checked without the fix, but that wasn't throwing errors for me for deploy modules. I do see this go wrong for deploy content or deploy schemas for instance. So, a good fix anyhow.

Small request though, I think it would be good to change ER into ERU in deploy_src as well, on this line:

```
      src_permissions = permissions(@properties['ml.app-role'], Roxy::ContentCapability::ER)
```

That is line 1447 at my end..

**Comment by joemfb** [comment]
Do merge commits get included in accepted pull requests? If so, this should probably be rebased.

First, to move this branch ahead of dev:

    git fetch upstream dev
    git rebase dev

Then, to remove the merge commits:

    git rebase -i dev

Remove any lines that aren't related to your PR, than save the commit.

**Comment by dmcassel** [comment]
@grtjn is this ready to be merged?

**Comment by jmeekhof** [comment]
I found another set of perms that need to be updated in server_config.rb. I'll update shortly.

**Comment by grtjn** [comment]
My comment is covered by PR #545 that should be piled on top of this one. I think we can merge both..

**Pull request merged**
